### PR TITLE
PyMeep 1.17.1

### PR DESCRIPTION
**Pull request by oskooi**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

@conda-forge-admin, please rerender.

### CODE REVIEW

**Comment by oskooi** [comment]
@RobinD42, there are some dependency conflicts causing build failures. Would you please take a look?

**Comment by RobinD42** [comment]
I'm not spotting any low-hanging fruit type of ideas or things to try, and I don't have time to dig any further at the moment. 

If you're not already I suggest doing local builds with docker and the generated `build_locally.py` script so you can do quicker iterations. Then fiddle with the versions of the dependencies (or remove them temporarily) for those that seem to be causing trouble. When you find a combination that works you can add the stricter dependencies back where they are needed.

**Comment by oskooi** [comment]
@conda-forge-admin, please rerender.

**Comment by bdice** [comment]
@conda-forge-admin, please rerender.

**Comment by bdice** [comment]
I'm triggering a re-render on this PR and #55 just to see if the build errors are similar or different. The build logs are too old to be shown, so hopefully a re-render will update the logs so I can try to debug.

**Comment by bdice** [comment]
@oskooi Helpful hint for next time: you _must_ use a personal fork like `oskooi/pymeep-feedstock` instead of a branch on the main feedstock repo `conda-forge/pymeep-feedstock`. The `pymeep_1.17.0` branch that you used to create this PR is on the main `conda-forge` repository, so it triggers package uploads for every commit even if the PR is not merged. I was guilty of this mistake as well, until I learned more about how the CI systems work: https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests

**Comment by oskooi** [comment]
Replaced by #56.

@bdice: Thanks for the reminder. Next time, I will create the PR from a branch on my personal fork.

**Pull request closed without merging**
