### PR TITLE
build meep with support for OpenMP

### PR DESCRIPTION
**Pull request by sheevy**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed) (@sheevy: not applicable)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering) (@sheevy: I've run `conda smithy rerender` but it was downgrading `hdf5` so I wans't sure if it's correct.)
* [ ] Ensured the license file is being packaged. (@sheevy: not sure how to check it, but given the nature of my change i hope it's ok)

### CODE REVIEW

**Comment by oskooi** [comment]
Note that Meep's support for thread-level parallelism using OpenMP is still an experimental feature as described in the docs under `--with-openmp`: https://meep.readthedocs.io/en/latest/Build_From_Source/#meep.

I would therefore prefer *not* to include this feature in the Conda package.

**Comment by sheevy** [comment]
Would you consider having it enabled, provided it's added as a new flavour of pymeep, alongisde nompi and mpimpich? So there would be a third option with support for both mpich and openmp.
Or you don't want to expose experimental feature at all?

**Comment by stevengj** [comment]
Since most OpenMP implementations *default* to using all of the cores, this is a bit dangerous for unsuspecting users (especially if they also use MPI).

**Comment by smartalecH** [comment]
I went through and added the openMP support to meep itself (at least to the timestepping kernels) -- and I don't recommend we package it. It's experimental, yes, but more importantly it's inferior to mpi itself (at least how we currently implemented it). There's too much overhead with the spawning, and a lot of cache contention.

I certainly wouldn't want to add it to the MPI build, because for users who aren't aware of the feature, and they don't set the default number of threads, then some flavors of openMP will default to all the cores and kill the performance.

**Comment by sheevy** [comment]
@smartalecH thanks for the context. I will close the PR then. 

For my curiosity, is there a performance penalty when using OpenMP enabled meep with `OMP_NUM_THREADS=1`?

**Comment by smartalecH** [comment]
@sheevy thanks for looking into this; sorry it didn't work out. 

Yep setting things to one thread should be fine. 

Ideally what we would want is mixed parallelism, where you launch one proc per node (or maybe even one proc per Numa bank, depending on your MPI flavor) and you use openmp to spawn as many threads as is allowed across the node/bank. 

But for this to pay off, we have to settle the cache contention issues by having each thread loop over a tile within the chunk (and leverage some of the cache-oblivious efforts). We also need to make sure we enforce first-touch, etc. 

From a performance perspective, I'm not sure it's worth the time investment (at least my time) since the gains won't be too significant (I usually hope for an order of magnitude...). 

But as @stevengj mentioned in our meeting, there are some practical use cases where this could help, like with large 3D optimizations where you don't want to duplicate your 3D array on each core/proc (and run out of memory).

**Pull request closed without merging**
