### PR TITLE
Add ppc64le support.

### PR DESCRIPTION
**Pull request by bdice**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by bdice** [comment]
@conda-forge-admin, please rerender

**Comment by bdice** [comment]
@oskooi It will take a couple hours for the mpb package updates to be deployed -- I'll come back to this PR.

**Comment by bdice** [comment]
@oskooi @ChristopherHogan It looks like some of the dependencies of pymeep don't have POWER / ARM builds enabled yet. Specifically `'hdf5==1.10.4[build=nompi_*]'`, `"libgdsii[version='>=0.21']"`, `'harminv'` are missing for one of the ARM builds. It looks like `libgdsii` and `harminv` are packages that you control and could update. The `hdf5` update is likely more complex and might require input from the conda-forge admins.

**Comment by bdice** [comment]
Looks like updating the HDF5 version from `1.10.4` to `>=1.10` fixed that dependency. I have open pull requests for `harminv` and `libgdsii` linked below. Merging those two should unblock this PR to pymeep.
- https://github.com/conda-forge/harminv-feedstock/pull/9
- https://github.com/conda-forge/libgdsii-feedstock/pull/4

**Comment by ChristopherHogan** [comment]
Looks good. I merged the harminv and libgdsii PRs, so this needs to be restarted once those are done and uploaded.

**Comment by bdice** [comment]
@ChristopherHogan @oskooi This package has too many dependencies for me to make it work with a reasonable amount of effort -- the tree is deep and broad, and relies on many packages that need to be updated for reasons beyond just ppc64le support. I tried to make PRs to `mayavi` and `h5utils` but both are failing because of dependencies. I don't think I can justify the time required to make all these work at the moment.

**Comment by oskooi** [comment]
Thanks for taking a stab at this. It would be nice for Meep to also support ppc64le. Hopefully, we can come back to this at some point.

**Comment by bdice** [comment]
If we decide to remove some of the "extras" in #56, I think it should be possible to compile meep for ppc64le and ARM. If so, I will re-create this PR after #56 is merged.

**Comment by bdice** [comment]
Closing, I no longer need this. If this feature is needed, it may be possible to do now that #56 has been merged.

**Pull request closed without merging**
